spring.application.name=intellectus
# Conexão SQLite
spring.datasource.url=jdbc:sqlite:intellectus.db?foreign_keys=on
spring.datasource.driver-class-name=org.sqlite.JDBC

# Dialeto Hibernate para SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Hibernate NÃO cria/altera tabelas (você vai fazer o SQL à mão)
spring.jpa.hibernate.ddl-auto=none

# Ver o SQL que o Hibernate gera (útil pra debug)
spring.jpa.show-sql=true
